// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBHpDgkET8B3XVnxYg50Yw3elnYqw8RGE',
    appId: '1:867537410975:web:6f537f52f968e9b38bbbaa',
    messagingSenderId: '867537410975',
    projectId: 'stamp-rally-360613',
    authDomain: 'stamp-rally-360613.firebaseapp.com',
    storageBucket: 'stamp-rally-360613.appspot.com',
    measurementId: 'G-DZBYXGSG2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl1gyPwSIMcownCEkXkAiI9ulWcDlLq9g',
    appId: '1:867537410975:android:9a01eb22b589d6798bbbaa',
    messagingSenderId: '867537410975',
    projectId: 'stamp-rally-360613',
    storageBucket: 'stamp-rally-360613.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKNcmzqra_6DTOeRUDPhy1j_opXy1laZQ',
    appId: '1:867537410975:ios:2f336b9d7da7c0978bbbaa',
    messagingSenderId: '867537410975',
    projectId: 'stamp-rally-360613',
    storageBucket: 'stamp-rally-360613.appspot.com',
    iosClientId: '867537410975-tcol00dpm001p12jtmbiljfaakrmb6r7.apps.googleusercontent.com',
    iosBundleId: 'com.example.stamprally',
  );
}
